on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: setup git user
        run: |
          git config --global user.name "gh-actions"
          git config --global user.email "actions@github.com"
      
      - name: create branch
        run: |
          git checkout --orphan ext-branch
          git rm -rf .
          git commit -a -m "Initial Commit"
          git push origin ext-branch
