on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: create branch
        run: |
          git checkout --orphan ext-branch
          git rm -rf .
          git add *
          git commit -a -m "Initial Commit"
          git push origin ext-branch
