on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: src
      
      - name: setup git user
        run: |
          git config --global user.name "gh-actions"
          git config --global user.email "actions@github.com"
      
      - uses: actions/checkout@v2
        with:
          ref: "ext-branch"
          path: docs
        
      - name: Run commands
        run: |
          ls -lh .
          ls -lh src
          ls -lh docs
          cp ./src/a.txt ./docs/*
          cd docs
          git commit -a -m "yujuuu"
          git push
