on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run commands
        run: |
          echo "hi"
          git config --global user.name "gh-actions"
          git config --global user.email "actions@github.com"
          git remote show
          git config user.name
          git config user.email
          echo "yepe" >> a.txt
          git add a.txt
          git commit -m "other yepe"
          git push
        env:
          GIT_PASS: ${{ secrets.GITHUB_TOKEN }}
