on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: setup git user
        run: |
          git config --global user.name "gh-actions"
          git config --global user.email "actions@github.com"
      
      - uses: actions/checkout@v2
        with:
          ref: "ext-branch"
          path: docs
        
      - name: Run commands
        run: |
          cp a.txt ../docs/
          cd ../docs
          git add *
